### ISSUE TITLE
Not a code issue, but you should probably credit Hyperium as well as I got my code from them (and edited it ofc, so that you don't need the 10k Hyperium classes.)

### ISSUE THREAD

**Issue by the-garbage-which-belongs-to-waffle** [Si1kn/auto-gg-mcp#1]
Title. (which is pretty long, so I'll copypaste it here: 

> **Not a code issue, but you should probably credit Hyperium as well as I got my code from them (and edited it ofc, so that you don't need the 10k Hyperium classes.).**

**Comment by Si1kn** [comment]
Yea thanks, i'll close this issue.
